import {
  FaBolt,
  FaFistRaised,
  FaFilm,
  FaLaughSquint,
  FaMask,
  FaScroll,
  FaSkull,
  FaMusic,
  FaTheaterMasks,
  FaRobot,
  FaTv,
  FaDragon,
  FaGhost,
  FaHeart,
  FaHatCowboy,
  FaUsers,
  FaQuestion,
  FaLandmark,
  FaGavel,
} from "react-icons/fa";

export const genreData = {
  28: { name: "Action", icon: <FaBolt />, color: "#ff5733" },
  12: { name: "Adventure", icon: <FaFistRaised />, color: "#ff8c00" },
  16: { name: "Animation", icon: <FaFilm />, color: "#ffcc00" },
  35: { name: "Comedy", icon: <FaLaughSquint />, color: "#33cc33" },
  80: { name: "Crime", icon: <FaMask />, color: "#b30000" },
  99: { name: "Documentary", icon: <FaScroll />, color: "#009999" },
  18: { name: "Drama", icon: <FaTheaterMasks />, color: "#800080" },
  10751: { name: "Family", icon: <FaUsers />, color: "#ff69b4" },
  14: { name: "Fantasy", icon: <FaDragon />, color: "#6600cc" },
  36: { name: "History", icon: <FaLandmark />, color: "#996633" },
  27: { name: "Horror", icon: <FaGhost />, color: "#000000" },
  10402: { name: "Music", icon: <FaMusic />, color: "#ff00ff" },
  9648: { name: "Mystery", icon: <FaQuestion />, color: "#333399" },
  10749: { name: "Romance", icon: <FaHeart />, color: "#ff1493" },
  878: { name: "Science Fiction", icon: <FaRobot />, color: "#00ccff" },
  10770: { name: "TV Movie", icon: <FaTv />, color: "#a52a2a" },
  53: { name: "Thriller", icon: <FaSkull />, color: "#4d4d4d" },
  10752: { name: "War", icon: <FaGavel />, color: "#8b0000" },
  37: { name: "Western", icon: <FaHatCowboy />, color: "#cd853f" },
};
